/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package hudson.android.monitor;

public final class R {
    public static final class array {
        public static final int refresh_rate_entries=0x7f050000;
        public static final int refresh_rate_values=0x7f050001;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int error=0x7f020000;
        public static final int failure=0x7f020001;
        public static final int ic_menu_refresh=0x7f020002;
        public static final int icon_32=0x7f020003;
        public static final int success=0x7f020004;
        public static final int success_g=0x7f020005;
        public static final int unknown=0x7f020006;
        public static final int warning=0x7f020007;
    }
    public static final class id {
        public static final int build_status_icon=0x7f070000;
        public static final int date=0x7f070003;
        public static final int line1=0x7f070001;
        public static final int status=0x7f070002;
    }
    public static final class layout {
        public static final int build_history=0x7f030000;
        public static final int build_history_list_item=0x7f030001;
    }
    public static final class string {
        public static final int about_button_close=0x7f060009;
        public static final int about_button_visit_site=0x7f060008;
        public static final int about_description=0x7f060007;
        public static final int about_title=0x7f060006;
        public static final int app_name=0x7f060000;
        public static final int app_url=0x7f060001;
        public static final int buildHistory_empty=0x7f060002;
        public static final int menu_about=0x7f060003;
        public static final int menu_refresh=0x7f060005;
        public static final int menu_settings=0x7f060004;
        public static final int preferences_add_server=0x7f06001b;
        public static final int preferences_check_for_updates=0x7f060019;
        public static final int preferences_debug_mode=0x7f060018;
        public static final int preferences_enable_notifications_title=0x7f06000f;
        public static final int preferences_green_for_success_title=0x7f060017;
        public static final int preferences_misc_title=0x7f060012;
        public static final int preferences_name=0x7f06000a;
        public static final int preferences_notifications_title=0x7f06000e;
        public static final int preferences_refresh_rate=0x7f06000c;
        public static final int preferences_refresh_title=0x7f06000b;
        public static final int preferences_select_ringtone_title=0x7f060010;
        public static final int preferences_server_password=0x7f060016;
        public static final int preferences_server_settings=0x7f060013;
        public static final int preferences_server_url=0x7f060014;
        public static final int preferences_server_username=0x7f060015;
        public static final int preferences_servers=0x7f06001a;
        public static final int preferences_vibrate=0x7f060011;
        public static final int preferences_wakeup_phone=0x7f06000d;
    }
    public static final class xml {
        public static final int preferences=0x7f040000;
    }
}
